import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <nav className="w-full bg-purple-900 border-b border-purple-900 py-4 px-6 flex justify-center gap-6 shadow-sm">
          <Link href="/servicos">
              <button className="bg-white text-black px-4 py-2 rounded-lg hover:bg-gray-300 transition">
                  Serviços
              </button>
          </Link>
          <Link href="/historico">
              <button className="bg-white text-black px-4 py-2 rounded-lg hover:bg-gray-300 transition">
                  Histórico
              </button>
          </Link>
      </nav>

        {children}

        <footer className="mt-10 w-full border-t border-gray-200 py-6 text-center text-sm text-gray-500">
            <p>Todos os direitos reservados</p>
            <p>Gabriel Marcolin</p>
            <p>2025</p>
        </footer>
      </body>
    </html>
  );
}